### ISSUE TITLE
config should use Result class names and not tables names

### ISSUE THREAD

**Issue by SysPete** [ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC#4]
Currently the config uses table names and camelizes them to try to get back to the original Class names. This is broken in the following example:

Result class: User
table: users

Camelizing `users` gives `Users` so the result class is not found. Please see https://metacpan.org/pod/Dancer::Plugin::Auth::Extensible::Provider::DBIC#CONFIGURATION for how D1 plugin does this in a more DBIC-friendly way.

Plugin also assumes that the relationship from User to UserRole class has the same name as the table name for UserRole which may not necessarily be true.

I am starting to build a new set of tests for D2 Auth::Extensible with classes that will be installed into @INC so will be available as a standard set of functionality tests for Provider classes. Will let you know when this is available as it will make testing your plugin much simpler and more reliable.

**Comment by abeverley** [comment]
Thanks Pete. I'm aware it's not perfect, and I need to look into it in more detail. However, as a quick reply, I think that given your example you can use `user` for the `users_table` config and it should work.

In terms of the D1 plugin, I did start with that, but I didn't like the way it did the configuration, as I felt that it over-configured things, making it longer to get things up and running. Like I say though, I need to look into it in more detail before commenting further. There is probably some mileage for a more fine-grained configuration available.

**Comment by abeverley** [comment]
Okay, I've still not looked in depth, but having had a cursory glance, I think I know why I did it like that. Things are more complicated than the D1 version, because the D2 version allows users to be created, including assigning them to roles.

Let's say you have a table `users` in your database. This would then likely be a `User` resultset. But, if you need to create a user's roles, then you will be using the `users` relationship. What I was trying to do, was prevent having to enter both.

Admittedly this does make assumptions about the name of a resultset and its relationship from the roles resultset, but I wonder whether anyone doesn't follow that convention? If they do, then yes it needs to be configured separately.

The config name `users_table` is misleading. It is more accurately the resultset/relationship. That needs documenting better, as this isn't the first time someone has had problems with it.

In terms of the original issue though, can you just configure with `user` instead of `users`?

**Comment by abeverley** [comment]
@SysPete - please see 47890fe. Does that work for you?

As per the commit message, I have renamed the config options to provide clarity as to what they are. I have also changed the defaults to something sensible, as per mailing list post.

For the reasons outlined above, I only require a minimal amount of config options to be specified, which will then generate the (normal) DBIC relationships etc. However, I have added additional options, should someone be using a non-standard naming convention.

**Comment by SysPete** [comment]
Closed by commit 47890fe9734856083733efcbe204e28c90d5c46d - many thanks @abeverley!
